import Head from 'next/head';
import Layout from '@/components/Layout';
import { Hero, About, Project, Contacts, Certificate } from '@/components';

import useData from '@/hooks/useData';

export default function Home() {
  const { data, isError, isLoading } = useData();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Layout
        dataHeader={data?.hero}
        dataFooter={data?.contacts}>
        <Hero data={data?.hero} />
        <About />
        <Project
          data={data?.categories}
          isLoading={isLoading}
          isError={isError}
        />
        <Certificate data={data?.certificate} />
        <Contacts />
      </Layout>
    </>
  );
}
